apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: linkup-backend
        image: backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: mongo-service
        - name: JWT_SECRET
          value: socialMediaIsReallyCool
        - name: PORT
          value: '3001'



---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      # nodePort: 30002
