apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: linkup-backend
        image: divyanshi2241/linkup-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        # - name: MONGO_URL
        #   value: 'mongodb://192.168.49.2:27017/social'
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: jwt-secret
        - name: PORT
          value: '3001'



---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30002
