apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: linkup-backend
        image: divyanshi2241/backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: mongo-service
        - name: JWT_SECRET
          value: socialMediaIsReallyCool
        - name: PORT
          value: '3001'
        - name: ELASTIC_USERNAME
          value: elastic
        - name: ELASTIC_PASSWORD
          value: gA7Zr9ZNHazQ3uFrJeLBXxtD
        - name: ELASTIC_CLOUD_ID
          value: 4c9b00c9b6bb4f859d07abe312d0d965:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyRmNWU1M2I4MTNlZjU0OGY5YmNhZTk5OTA5M2QzNmQ3ZSRmMWY4M2Q2YzE0ZDI0YjU0YTI4MzAyYmY0MDdhNmU2Ng==
        volumeMounts:
              - name: varlog
                mountPath: /var/log
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
# gmqaoxtlwxptddzwnr@tpwlb.com
# Nikhil@8758

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      # nodePort: 30002
